### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by twenzel** [awaescher/Fusion#10]
Please add the support for .NET Core Applications.

Details: https://github.com/dotnet/coreclr/issues/10379

**Comment by awaescher** [comment]
On radar. But I still miss a clean approach in .NET Core. It seems not to be finalized yet.

Tracking this as well: https://twitter.com/matthewwarren/status/1195350818414874626?s=21

**Comment by awaescher** [comment]
Things are getting interesting in .NET 5 ... 

https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-1/

![6EE32683-B6A0-405E-85A9-8E194A51820E](https://user-images.githubusercontent.com/3630638/76803924-41f07d80-67db-11ea-8fdc-c3a570682e9a.jpeg)

**Comment by awaescher** [comment]
https://github.com/richlander/testapps/tree/master/trace-assembly-loading

**Comment by awaescher** [comment]
https://github.com/richlander/testapps/blob/master/trace-assembly-loading/README.md

**Comment by bitbonk** [comment]
Just curious: Did you close this issue because you do not plan to implement a nice UI for this for .NET (Core) in Fusion?
