### ISSUE TITLE
Can't run on Win7 32-bit

### ISSUE THREAD

**Issue by avenmore** [awaescher/Fusion#13]
Windows error:
The version of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

This is where I need the Fusion log viewer: on a VM to test that I have all dependencies included in my build and to help find the missing ones.

Am I missing something or can I really not run the app in this environment?

**Comment by awaescher** [comment]
New to me. I did a rewrite in version 1.2 in .NET Core. Can you try version 1.1 from the releases tab? That one was built using the full framework.

Would be nice if you could provide feedback on this.

**Comment by avenmore** [comment]
Just tried installing "aspnetcore-runtime-3.0.3-win-x86.exe", but same error. Will try 1.1.

**Comment by avenmore** [comment]
Tried installing "dotnet-runtime-3.0.3-win-x86.exe" but same error. Will try 1.1.

**Comment by awaescher** [comment]
Please try 1.1. As said, this version was built with the good old Full-Framework (v4.7.2). You might need to install the v4.7.2 runtime if your Windows image is plain vanilla.

**Comment by avenmore** [comment]
1.1 runs fine. I tried to log 1.2's startup with 1.1 but it is halted before logging starts.

**Comment by awaescher** [comment]
Thanks for the report. I will have a look at this.

Yes, you can‘t log .NET Core apps with Fusion++ or FUSLOGVW, Microsoft changed pretty much everything about assembly loading in .NET Core. It might be applicable to .NET 5 again, see [issue10](https://github.com/awaescher/Fusion/issues/10).

**Comment by avenmore** [comment]
Thanks - it's looking like a great tool - am going to have fun exploring my apps with it.

**Comment by awaescher** [comment]
![image](https://user-images.githubusercontent.com/3630638/77001386-2790de00-695a-11ea-9476-589f66f2d5eb.png)

**Comment by awaescher** [comment]
News on this?
