### ISSUE TITLE
It would be better if you can include the timezone info in log folder

### ISSUE THREAD

**Issue by chucklu** [awaescher/Fusion#15]
C:\Users\clu\AppData\Local\Temp\Fusion++\2020.04.29.07.47.14.7452\Default\Everything.exe
can be convert to 
C:\Users\clu\AppData\Local\Temp\Fusion++\2020.04.29.15.47.14.7452+0800\Default\Everything.exe

```C#
private const string DATE_FORMAT = "yyyy.MM.dd.HH.mm.ss.ffffzzz";
var folder=DateTime.Now.ToString(DATE_FORMAT).Replace(":", string.Empty);
Path = System.IO.Path.Combine(TopLevelPath, folder);
```

The following parse datetime will not work. maybe write a custom method to parse the time.
```C#
	if (DateTime.TryParseExact(result, UTC_DATE_FORMAT, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.AssumeUniversal, out DateTime date))
				result = date.ToShortDateString() + " " + date.ToLongTimeString();
````

**Comment by awaescher** [comment]
Why do you want me to add the time zone to an UTC date?

**Comment by awaescher** [comment]
In addition, this one is not releated to #16 so I'm closing it.

**Comment by chucklu** [comment]
@awaescher The problem is the time on personal computer is not the UTC time.
The standard behavior is record the time with timezone
log4net component can record log with timezone info
```xml
<conversionPattern value="[%d{dd MMM yyyy HH:mm:ss.fff**zzz**}{GMT}] [%5level] (%identity-%username) %message%newline" />
```

**Comment by awaescher** [comment]
![image](https://user-images.githubusercontent.com/3630638/82308032-80fca400-99c1-11ea-943e-93dcf244605a.png)
