### ISSUE TITLE
The temp folder lack of permission

### ISSUE THREAD

**Issue by chucklu** [awaescher/Fusion#19]
Today I tried to get the log of another application, and I can not get the log detail.
And I checked C:\Users\username\AppData\Local\Temp\Fusion++, and it did not have everyone permission.

**Comment by chucklu** [comment]
add everyone permission manually still did not work.
Tried to restart the application pool, then I got the log detail.

**Comment by awaescher** [comment]
I don't understand, could you please clarify?

**Comment by chucklu** [comment]
After I run Fusion++.exe, and click record button. Then Fusion++.exe will create a temp folder   C:\Users\username\AppData\Local\Temp\Fusion++, and set log path of Fuslogvw.exe to the temp folder.
And the temp folder expected to have everyone write permission.

Currently the folder did not have the everyone permission.

**Comment by chucklu** [comment]
everyone means the specific user group
https://security.stackexchange.com/questions/23600/potential-consequences-of-using-everyone-to-manage-permissions
