### ISSUE TITLE
Cannot build - NuGet not available: DevExpress.RichEdit.Core 18.2.7

### ISSUE THREAD

**Issue by petritis-at-work** [awaescher/Fusion#2]
I was not able to build because Visual Studio could not get:
DevExpress.RichEdit.Core 18.2.7
I could not find it on NuGet.

Here is what VS said:

```
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the NuGet Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
NuGet Package restore failed for project Fusion++: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to find version '18.2.7' of package 'DevExpress.RichEdit.Core'.
```

**Comment by awaescher** [comment]
To restore the DevExpress NuGet packages, you have to obtain your own DevExpress feed and add it to the NuGet package sources in Visual Studio. However, this requires you to own a DevExpress subscription:

- https://documentation.devexpress.com/GeneralInformation/116042/Installation/Install-DevExpress-Controls-Using-NuGet-Packages/Obtain-Your-NuGet-Feed-URL

I suggest to download the compiled release [from the releases page](https://github.com/awaescher/Fusion/releases).
