### ISSUE TITLE
UI bug - Can't import fusion logs without creating a Fusion++ session

### ISSUE THREAD

**Issue by jzebedee** [awaescher/Fusion#21]
I can't see a way to view existing fusion logs stored on the filesystem, except those recorded and tracked by Fusion++. I was hoping for something similar to fuslogvw, where you can pass in an arbitrary log folder path to view the logs inside.

**Comment by jzebedee** [comment]
OK, it looks like the option to import a folder doesn't appear until you create a session within Fusion++ first:

![image](https://user-images.githubusercontent.com/1896945/92522790-e5e44000-f1e4-11ea-8649-1ff18be017bc.png)

**Comment by jzebedee** [comment]
After creating any session:

![image](https://user-images.githubusercontent.com/1896945/92522947-2479fa80-f1e5-11ea-8111-a69d057a8ec1.png)

**Comment by awaescher** [comment]
[Version 1.4](https://github.com/awaescher/Fusion/releases/tag/v1.4) was just released 🎉

Thank you for the feedback.
