### ISSUE TITLE
UX request - Add open session to title

### ISSUE THREAD

**Issue by jzebedee** [awaescher/Fusion#22]
Since you can only have one session open at a time per Fusion++ instance, it would be helpful to add the session name to the title. It's easy to lose track while switching through several sessions, because there's no visual indicator for the name of the currently open session.

**Comment by awaescher** [comment]
Well you could easily rename the folders after clicking on "Show in Windows Explorer".

However, Fusion++ will append the process names anyways and sort the list by the name in descending order because he expects the folders to be named with a given datetime pattern.

**Comment by awaescher** [comment]
Oh I'm sorry, I thought this was about the session dropdown list. Okay now ... we're talking about the form title, right?
Would it help to add the session name from the dropdown list which is kind of verbose sometimes?

**Comment by jzebedee** [comment]
> Oh I'm sorry, I thought this was about the session dropdown list. Okay now ... we're talking about the form title, right?
> Would it help to add the session name from the dropdown list which is kind of verbose sometimes?

Yeah, that would be great! All I had in mind was using the session name (from dropdown list) or the folder path and having it in the title / visible somewhere on-screen.

**Comment by awaescher** [comment]
Took me a while to get at this (sorry) but I got you

![image](https://user-images.githubusercontent.com/3630638/114320164-e810d300-9b14-11eb-9bc0-c21aa94f130f.png)

**Comment by awaescher** [comment]
[Version 1.4](https://github.com/awaescher/Fusion/releases/tag/v1.4) was just released 🎉

Thank you for the feedback.
