### ISSUE TITLE
Support WhereRefBind log entries

### ISSUE THREAD

**Issue by KirillOsenkov** [awaescher/Fusion#24]
I've been using Fusion++ today, it's a great tool!

I noticed that it looks like it may not support all entries. Specifically if I run fuslogvw.exe and specify log all binds to disk, I may get files with this format: `WhereRefBind!Host=(LocalMachine)!FileName=(Microsoft.Build.NuGetSdkResolver.dll).htm`

These don't seem available in Fusion++.

To get a repro:
1. `git clone https://github.com/dotnet/msbuild` (assuming you cloned into C:\MSBuild), checkout main as of 2021-03-24 (e.g. https://github.com/dotnet/msbuild/commit/bf0b0c52351d2034daec62b74c49f67def7fe739)
2. `build -bl /p:CreateBootstrap=true`
3. `C:\msbuild\artifacts\bin\bootstrap\net472\MSBuild\Current\Bin\MSBuild.exe /r C:\temp\net472\net472.csproj` where net472.csproj is any dotnet C# project. Note /r is important as the codepaths involve NuGet

Run step 3 under fuslogvw and Fusion++ and compare the results.

https://github.com/dotnet/msbuild/issues/6289 is the issue we're investigating. Looks like we first load an assembly using Assembly.LoadFrom(), which loads it into the LoadFrom context, then we load the same .dll into the default load context, so we have two copies of the assembly loaded from two different codepaths, then we get the exception.

**Comment by awaescher** [comment]
Whoa, great spot. I will have a look at this soon.
Thanks for the feedback.

**Comment by awaescher** [comment]
Fusion++ checks if it was able to parse log entries by looking if the corresponding entry has a DisplayName. 

This is okay for "ordinary" logs like this:

```
=== Zustandsinformationen vor Bindung ===
LOG: DisplayName = System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
 (Fully-specified)
LOG: Appbase = file:///D:/Develop/GitHub/msbuild/artifacts/bin/bootstrap/net472/MSBuild/Current/Bin/
LOG: Ursprünglicher PrivatePath = NULL
LOG: DynamicBase = NULL
LOG: CacheBase = NULL
LOG: AppName = MSBuild.exe
Aufruf von Assembly : Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
```

See `DisplayName = System.Xml.Linq ...`

For Where-Ref binds, there's no DisplayName. That's why Fusion++ sorts them out.

```

=== Zustandsinformationen vor Bindung ===
LOG: Where-ref-Bindung. Speicherort = D:\Develop\GitHub\msbuild\artifacts\bin\bootstrap\net472\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\tools\net472\Microsoft.NET.Build.Extensions.Tasks.dll
LOG: Appbase = file:///D:/Develop/GitHub/msbuild/artifacts/bin/bootstrap/net472/MSBuild/Current/Bin/
LOG: Ursprünglicher PrivatePath = NULL
LOG: DynamicBase = NULL
LOG: CacheBase = NULL
LOG: AppName = MSBuild.exe
Aufruf von Assembly : (Unknown).
===
```

What would you say could be the DisplayName for Where-Ref bindings? 

![image](https://user-images.githubusercontent.com/3630638/114318766-d62c3180-9b0e-11eb-9c1f-c32f4dddc410.png)

**Comment by awaescher** [comment]
What do you think about this?

![image](https://user-images.githubusercontent.com/3630638/114319231-e8a76a80-9b10-11eb-90f5-9b4161728eba.png)

**Comment by KirillOsenkov** [comment]
This is perfect! Thanks so much!

**Comment by awaescher** [comment]
[Version 1.4](https://github.com/awaescher/Fusion/releases/tag/v1.4) was just released 🎉

Thank you for the feedback, Kirill.

**Comment by Eruvisu** [comment]
Can someone tell me what "Where-ref bindings" are? Or where can I find some information about it?
I searched a bit on the internet but I wasn't able to find anything.
I have an issue with one dll where it searches for it in the probing paths and it doesn't find it but then it finds it using 'where-ref'.
And then for the same dll in another application it doesn't use `where-ref`. It just searches for it in the probing paths and it doesn't find it and that's it.
I used Fusion++ v1.4.

**Comment by KirillOsenkov** [comment]
Maybe @davkean knows?

**Comment by davkean** [comment]
WhereRef binds are situations where the assembly name hasn't been set; think Assembly.LoadFrom("foo.dll").

**Comment by Eruvisu** [comment]
Thanks @davkean  for the explanation.
