### ISSUE TITLE
No issue - just a thanks

### ISSUE THREAD

**Issue by Saltallica** [awaescher/Fusion#31]
THANK FUCKING GOD. 
STUMBLING ON TO THIS SAVED MY SANITY.
I HAD THE FUSION LOGGER IN VERBOSE FOR ***YEARS*** AND DIDN'T REALIZE IT
I THOUGHT LOADING ASSEMBLIES THROUGH REFLECTION WAS REALLY SLOW
TURNS OUT,  I'M THE SLOW ONE.

GOD BLESS YOU.

**Comment by awaescher** [comment]
Thanks for your feedback, really happy I could help you with this 😄
