### ISSUE TITLE
Publish the tool on winget

### ISSUE THREAD

**Issue by InKahootz** [awaescher/Fusion#39]
It would be awesome if this tool was able to be installed via `winget`.

I can submit a PR to the [winget-pkgs](https://github.com/microsoft/winget-pkgs) to get it listed!  
I did this for msbuild structured log viewer as well: https://github.com/microsoft/winget-pkgs/pull/28191

However, winget currently doesn't support portable executables or zip files. So an actual installer would need to be created first.

Once the initial is put in, the winget-pkgs-bot will keep it updated when you do a release on GitHub.

Sound like a good idea?

**Comment by awaescher** [comment]
Sounds like a good idea and I'd support this one. However I am not planning to build an installer upfront.
