### ISSUE TITLE
ARM64 version

### ISSUE THREAD

**Issue by ghost** [awaescher/Fusion#41]
Hi,

First of all, thank you for this tremendously useful tool! It has been part of my troubleshooting toolchain for quite some time 😊

Since Fusion++ is now published self-contained, I wanted to ask if it would be possible to publish an ARM64 package as well. Windows ARM64 is beginning to take off, and the company I work at is now getting first bug reports from customers on ARM64. It would've been great if Fusion++ was available natively on that platform.

Thank you!

**Comment by awaescher** [comment]
Thanks for the feedback.
You mean analysing .NET Framework (not .NET Core, 5+) apps on ARM64?

**Comment by ghost** [comment]
Hi, no I mean publishing Fusion++ itself as an ARM64 app. Right now it's an x64 self-contained archive ([Fusion++.1.5.zip](https://github.com/awaescher/Fusion/releases/download/v1.5/Fusion++.1.5.zip)), would be great to have an ARM64 archive as well.

**Comment by awaescher** [comment]
Could be done but I guess it would not make a big difference out there. Fusion logging is not supported with .NET Core and .NET 5+. I guess classic .NET Framework is not heavily used on ARM64 though it's possible with .NET Framework 4.8.1.

That being said, I think you'd mostly analyse dumps from other machines on your ARM64 machine. 

Would be awesome to get a pull-request for this.

**Comment by awaescher** [comment]
Closed because of inactivity. Feel free to re-open.
