### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by mitnick2012** [awaescher/Fusion#42]
can you provide a Linux version of the app? it will be very useful.

**Comment by awaescher** [comment]
Fusion logging is only available in .NET Framework not the "new" .NET (aka .NET Core) which is Windows exclusive.
Therefore I can't see how this could be helpful.

**Comment by mitnick2012** [comment]
it will be helpful for people working with .Net on Linux , I converted a software to Linux and debugging on Ubuntu, I had issue of assembly binding issue but can't find a good tool that can do the task.
