### ISSUE TITLE
Can't build - Requires DevExpress subscription?

### ISSUE THREAD

**Issue by brucecbourdon** [awaescher/Fusion#5]
This looks like it could be very helpful but I am unable to build it without paying a thousand dollars or more for the DevExpress tools. Is there a workaround?

PS: The code has a dependency on many DevExpress v18.2 asseblies, the current version is 19.x.

Would love to try out this tool, if not for the extreme expense for the requirements.
Bruce.

**Comment by awaescher** [comment]
Hi Bruce. There‘s no way to make that possible without violating the DevExpress license agreeement: You need a subscription to build apps with it.
However, it‘s okay to redistribute the DevExpress-assemblies with the built application. That‘s why you can easily take a prebuilt version from the [releases tab](https://github.com/awaescher/Fusion/releases).
